### ISSUE TITLE
free(): invalid pointer Error

### ISSUE THREAD

**Issue by Lapsis-glitch** [qcxms/QCxMS#83]
Hi!
I have been trying to get QCxMS to run on a couple of workstations and keep running into this error when trying to perform the production runs with either `pqcxms` or with `qcxms --prod` in the individual folders:

>free(): invalid pointer
>
>Program received signal SIGABRT: Process abort signal.
>
>Backtrace for this error:
>#0  0x15160434208f in ???
>       at /build/glibc-wuryBv/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
>#1  0x15160434200b in __GI_raise
>        at ../sysdeps/unix/sysv/linux/raise.c:51
>#2  0x151604321858 in __GI_abort
>        at /build/glibc-wuryBv/glibc-2.31/stdlib/abort.c:79
>#3  0x15160438c26d in __libc_message
>        at ../sysdeps/posix/libc_fatal.c:155
>#4  0x1516043942fb in malloc_printerr
>        at /build/glibc-wuryBv/glibc-2.31/malloc/malloc.c:5347
>#5  0x151604395b2b in _int_free
>        at /build/glibc-wuryBv/glibc-2.31/malloc/malloc.c:4173
>#6  0x55770d40305e in ???
>#7  0x55770d3ce536 in ???
>#8  0x55770d3c8060 in ???
>#9  0x151604323082 in __libc_start_main
>        at ../csu/libc-start.c:308
>#10  0x55770d3c8090 in ???

I increased the OMP stack size and used `ulimit -s unlimited` but still get the crashes. I tried compiling from scratch (with gcc) from the master branch, but the results are the same as with the conda version, even on different machines. I tried it on ubuntu 20.04, ubuntu 22.04, as well as clear linux 40130. I attached the input and output files below.

Can you help me try to pin down the source of the error?

[qcxms.in.txt](https://github.com/qcxms/QCxMS/files/13687452/qcxms.in.txt)
[qcxms.out.txt](https://github.com/qcxms/QCxMS/files/13687457/qcxms.out.txt)
[start.xyz.txt](https://github.com/qcxms/QCxMS/files/13687618/start.xyz.txt)

**Comment by tornikeo** [comment]
Possibly related to #88
