### ISSUE TITLE
conda package maybe broken?

### ISSUE THREAD

**Issue by st1553** [qcxms/QCxMS#85]
No matter what I do, the conda packaged version of this always seems to give this error when run with a coord file and qxcms.in:

```
-- linux-rhel9-zen3 / gcc@11.4.1 --------------------------------
py-conda-souschef@2.2.3  qcxms@5.2.1
==> 2 installed packages
Input file content (qcxms.in):
xtb
ntraj 300
tmax  10
tinit 500
ieeatm 0.6
Coordinate file content (coord):
$coord
O          3.05620       -3.62856       -0.37084
C          1.84105       -3.44086       -0.31115
N          1.25506       -2.34517       -0.90928
C          2.07206       -1.42471       -1.69967
C          2.96825       -0.61734       -0.72802
N          4.31233       -0.86051       -0.84134
O          2.55427        0.16498        0.12254
C          1.26294       -0.50658       -2.66588
C          2.21210        0.47721       -3.38791
C          0.58830       -1.37105       -3.75259
C          0.17726        0.30535       -1.93882
C          0.92150       -4.40831        0.31119
N         -0.25407       -4.09763        0.89368
N         -0.69947       -5.28629        1.40485
C         -1.87948       -5.24455        2.27729
C         -2.38327       -6.59256        2.79486
C         -3.61027       -6.55377        3.70211
C         -3.98173       -7.97964        4.10955
C          0.07434       -6.36624        1.01539
C          1.14998       -5.80882        0.32615
C          2.15367       -6.64503       -0.20620
C          2.05996       -8.02530       -0.05077
C          0.98991       -8.57447        0.63830
C         -0.00925       -7.76124        1.18350
H          2.73473       -2.04977       -2.31702
H          0.24923       -2.25331       -0.82982
H          4.86569       -0.44249       -0.10562
H          4.58539       -1.80873       -1.08901
H          2.98696       -0.05781       -3.94908
H          2.71287        1.15238       -2.68606
H          1.66283        1.10513       -4.09917
H          1.33331       -1.92309       -4.33781
H          0.01933       -0.74857       -4.45366
H         -0.10517       -2.09893       -3.31962
H          0.60809        0.99727       -1.20956
H         -0.53220       -0.34099       -1.41347
H         -0.40021        0.90823       -2.64886
H         -2.66964       -4.74284        1.70602
H         -1.60830       -4.60072        3.12339
H         -1.57703       -7.07662        3.35899
H         -2.63867       -7.22065        1.93388
H         -4.45621       -6.09361        3.18073
H         -3.40568       -5.96104        4.60004
H         -4.19587       -8.59547        3.22849
H         -4.86715       -7.98712        4.75121
H         -3.16098       -8.45698        4.65705
H          2.99158       -6.21565       -0.75001
H          2.82569       -8.66882       -0.47426
H          0.92310       -9.65304        0.75758
H         -0.81858       -8.25029        1.70941
$end
Generating ground state (GS) trajectory...
Mon Jul 22 10:12:22 PM EDT 2024


                      *********************************************
                      *                                           *
                      *            Q   C   x   M   S              *
                      *                                           *
                      *                  V5.2.1                   *
                      *        Sep 20 18:00:00 CEST 2022          *
                      *                                           *
                      *                S. Grimme                  *
                      *                J. Koopman                 *
                      * Mulliken Center for Theoretical Chemistry *
                      *             Universitaet Bonn             *
                      *                                           *
                      *********************************************

 QCxMS is free software: you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 QCxMS is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

Cite this work as:
S.Grimme, Angew.Chem.Int.Ed. 52 (2013) 6306-6312.

for the CID module:
J. Koopman, S. Grimme, J. Am. Soc. Mass Spectrom., (2021),  DOI: 10.1021/jasms.1c00098

with respect to negative/multiple charges:
J. Koopman, S. Grimme, ChemRxiv, (2022),  DOI: 10.26434/chemrxiv-2022-w5260

for the GFN1-xTB implementation:
V. Asgeirsson, C.Bauer, S. Grimme, Chem. Sci. 8 (2017) 4879

for the GFN2-xTB implementation:
 J. Koopman, S. Grimme, ACS Omega 4 (12) (2019) 15120-15133,  DOI: 10.1021/acsomega.9b02011

 changed by input:
>xtb
>ntraj 300
>tmax  10
>tinit 500
>ieeatm 0.6
ERROR STOP  -- Unrecognized Keyword --

Error termination. Backtrace:
#0  0x5556c90fd6d5 in ???
#1  0x5556c90d36df in ???
#2  0x5556c90d3060 in ???
#3  0x7ffabe03feaf in ???
#4  0x7ffabe03ff5f in ???
#5  0x5556c90d3090 in ???
qcxms command failed during GS trajectory generation.
```

**Comment by tobigithub** [comment]
@st1553

**Comment by st1553** [comment]
Thank you so much Tobias that fixed the issue. Can close the ticket thank
you
